// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-XjVoj71xB1czQlx9hjwBVxyNEFtiWQY',
    appId: '1:510681806929:web:159ab0b345e9027bf16070',
    messagingSenderId: '510681806929',
    projectId: 'guardapp-ab846',
    authDomain: 'guardapp-ab846.firebaseapp.com',
    storageBucket: 'guardapp-ab846.firebasestorage.app',
    measurementId: 'G-3KZ5JWDE9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyONjydC18PqSnMRIhcRPf5mcF3w1MjM',
    appId: '1:510681806929:android:306a5012c8837073f16070',
    messagingSenderId: '510681806929',
    projectId: 'guardapp-ab846',
    storageBucket: 'guardapp-ab846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd4DCmMru0JJXOqTgkzZyKM16s-Wcz3iI',
    appId: '1:510681806929:ios:a94fedf699cc33cdf16070',
    messagingSenderId: '510681806929',
    projectId: 'guardapp-ab846',
    storageBucket: 'guardapp-ab846.firebasestorage.app',
    iosBundleId: 'com.example.guardapp',
  );
}
